
package day67webservice.demo3.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonServer", targetNamespace = "http://demo3.day67webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonServer {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPersion", targetNamespace = "http://demo3.day67webservice/", className = "day67webservice.demo3.stub.AddPersion")
    @ResponseWrapper(localName = "addPersionResponse", targetNamespace = "http://demo3.day67webservice/", className = "day67webservice.demo3.stub.AddPersionResponse")
    @Action(input = "http://demo3.day67webservice/PersonServer/addPersionRequest", output = "http://demo3.day67webservice/PersonServer/addPersionResponse")
    public void addPersion(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<day67webservice.demo3.stub.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonAll", targetNamespace = "http://demo3.day67webservice/", className = "day67webservice.demo3.stub.GetPersonAll")
    @ResponseWrapper(localName = "getPersonAllResponse", targetNamespace = "http://demo3.day67webservice/", className = "day67webservice.demo3.stub.GetPersonAllResponse")
    @Action(input = "http://demo3.day67webservice/PersonServer/getPersonAllRequest", output = "http://demo3.day67webservice/PersonServer/getPersonAllResponse")
    public List<Person> getPersonAll();

}
