
package day68webservice.demo1client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JobServiceImplService", targetNamespace = "http://demo1service.day68webservice/", wsdlLocation = "http://192.168.1.101:8092/job?wsdl")
public class JobServiceImplService
    extends Service
{

    private final static URL JOBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName JOBSERVICEIMPLSERVICE_QNAME = new QName("http://demo1service.day68webservice/", "JobServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.101:8092/job?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        JOBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public JobServiceImplService() {
        super(__getWsdlLocation(), JOBSERVICEIMPLSERVICE_QNAME);
    }

    public JobServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOBSERVICEIMPLSERVICE_QNAME, features);
    }

    public JobServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, JOBSERVICEIMPLSERVICE_QNAME);
    }

    public JobServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOBSERVICEIMPLSERVICE_QNAME, features);
    }

    public JobServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JobService
     */
    @WebEndpoint(name = "JobServiceImplPort")
    public JobService getJobServiceImplPort() {
        return super.getPort(new QName("http://demo1service.day68webservice/", "JobServiceImplPort"), JobService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobService
     */
    @WebEndpoint(name = "JobServiceImplPort")
    public JobService getJobServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo1service.day68webservice/", "JobServiceImplPort"), JobService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw JOBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return JOBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
