
package day68webservice.deom1client.stub;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JobService", targetNamespace = "http://demo1service.day68webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JobService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJob", targetNamespace = "http://demo1service.day68webservice/", className = "day68webservice.deom1client.stub.GetJob")
    @ResponseWrapper(localName = "getJobResponse", targetNamespace = "http://demo1service.day68webservice/", className = "day68webservice.deom1client.stub.GetJobResponse")
    @Action(input = "http://demo1service.day68webservice/JobService/getJobRequest", output = "http://demo1service.day68webservice/JobService/getJobResponse")
    public String getJob();

}
